services:
  - name: client
    type: web
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: npm run dev  # Adjust if needed
    envVars:
      - key: NODE_ENV
        value: production

  - name: server
    type: web
    buildCommand: |
      cd server
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
